server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      properties:
        enable.idempotence: true
        linger.ms: 5
        retries: 10
    consumer:
      group-id: saga-platform
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
platform:
  event:
    source-service: saga-platform
app:
  outbox:
    batch-size: 50
    fixed-delay-ms: 3000
